version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./server
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVICE}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@${REDIS_SERVICE}:${REDIS_PORT}
      - LOGS_LEVEL=${LOGS_LEVEL}
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - postgres
      - redis
  
  postgres:
    container_name: ${POSTGRES_SERVICE}
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  redis:
    container_name: ${REDIS_SERVICE}
    image: redis:alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
