version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./server
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVICE}:${POSTGRES_PORT}/${POSTGRES_DB}?pool_timeout=30&connect_timeout=10
      - LOGS_LEVEL=${LOGS_LEVEL}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - postgres
  
  postgres:
    container_name: ${POSTGRES_SERVICE}
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
